{
 "title": "blllllllllackkkk",
 "tags": [
  "aaaaaaaaaa",
  "vvvvvvv",
  "dddddddd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(probe_success,job)"
   },
   {
    "name": "host",
    "label": "host",
    "query": "label_values(probe_success{job=~\"$job.*\"},job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Endpoint",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(probe_success{job =~\"$job(_ip_)$host\"})"
    }
   ]
  },
  {
   "title": "Endpoint Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count (probe_success{job=~\"$job(_ip_)$host\"} > 0)"
    }
   ]
  },
  {
   "title": "Endpoint Down",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count (probe_success{job=~\"$job(_ip_)$host\"} < 1)"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sort_desc(probe_success{job=~\"$job(_ip_)$host\"})"
    }
   ]
  },
  {
   "title": "Total Change (1day)",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 5 },
   "targets": [
    {
     "expr": "sort(changes(probe_success{job=~\"$job(_ip_)$host\"}[24h]))"
    }
   ]
  },
  {
   "title": "Status Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(probe_success{job=~\"$job(_ip_)$host\"}[24h]) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Event List",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job(_ip_)$host\"} and changes(probe_success{job=~\"$job(_ip_)$host\"}[24h]) > 0"
    }
   ]
  }
 ]
}